/**
 * Regression report for the deterministic classifier.
 *
 *   npm run calibrate:rules
 *
 * Runs every corpus case through `classifyUserMove` and reports agreement,
 * split by corpus so the two are never averaged together:
 *
 *   authored — cases written by the author of the rules. High agreement here
 *              means the rules do what their author meant. It is a refactor
 *              guard. It is NOT an accuracy measurement, and reporting it as
 *              one would be the exact kind of overclaim this project keeps
 *              telling itself not to make.
 *
 *   field    — messages typed by a real user during a TRAIN session, labelled
 *              afterwards. This is the set that can say something about
 *              accuracy. It starts empty; fill it as you go.
 *
 * Exits non-zero if any AUTHORED case disagrees, so a refactor that silently
 * changes classification fails the build. Field disagreements are reported but
 * never fail the build — a real user writing something the rules mishandle is
 * information, not a regression.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { classifyUserMove, type MoveType } from '../src/lib/state_rules';

const here = dirname(fileURLToPath(import.meta.url));
const corpusPath = join(here, '..', 'corpus', 'user_moves.json');
const outPath = join(here, '..', 'docs', 'classifier_report.md');

interface MoveCase {
  id: string;
  expect: MoveType;
  message: string;
}

interface Row extends MoveCase {
  got: MoveType;
  agrees: boolean;
  alsoMatched: MoveType[];
}

function evaluate(cases: MoveCase[]): Row[] {
  return cases.map((c) => {
    const r = classifyUserMove(c.message);
    return { ...c, got: r.moveType, agrees: r.moveType === c.expect, alsoMatched: r.alsoMatched };
  });
}

function table(rows: Row[]): string {
  if (!rows.length) return '_(empty)_\n';
  return [
    '| Case | Message | Expected | Classified | |',
    '|---|---|---|---|---|',
    ...rows.map(
      (r) =>
        `| \`${r.id}\` | ${JSON.stringify(r.message).slice(0, 70).replace(/\|/g, '\\|')} | \`${r.expect}\` | \`${r.got}\` | ${r.agrees ? 'agrees' : '**DIFFERS**'} |`,
    ),
  ].join('\n');
}

function rate(rows: Row[]): string {
  if (!rows.length) return 'n/a (no cases)';
  const n = rows.filter((r) => r.agrees).length;
  return `${n}/${rows.length} (${Math.round((n / rows.length) * 100)}%)`;
}

function main() {
  const corpus = JSON.parse(readFileSync(corpusPath, 'utf8')) as {
    authored: MoveCase[];
    field: MoveCase[];
  };

  const authored = evaluate(corpus.authored);
  const field = evaluate(corpus.field ?? []);

  const doc = `# Classifier regression report

Generated by \`npm run calibrate:rules\`.

## Read this before quoting a number from this file

The two corpora below measure different things and must never be added
together.

**Authored** cases were written by the author of the rule table. Agreement
here says the implementation matches its author's intent — it is a guard
against a refactor changing behaviour silently. It says nothing about whether
a negotiation coach would agree with the labels, because the same person chose
both the label and the rule that produces it.

**Field** cases are messages a real user typed during a TRAIN session,
labelled afterwards. Only this set can support a claim about accuracy, and
only once it is large enough to be worth quoting. It is currently
${field.length === 0 ? '**empty**, so no accuracy claim is available at all' : `${field.length} case(s), which is still small`}.

| Corpus | Agreement | What it licenses you to say |
|---|---|---|
| Authored | ${rate(authored)} | "The engine behaves as specified." |
| Field | ${rate(field)} | ${field.length ? '"On N real messages, the engine agreed with the user\'s own labelling M times."' : '_Nothing yet._'} |

## Authored corpus

${table(authored)}

## Field corpus

${table(field)}

## How to grow the field corpus

During a TRAIN session, when the engine labels one of your moves in a way that
surprises you, copy the message into \`corpus/user_moves.json\` under
\`field\` with the label you think is right. Do not adjust the rules to match
it on the spot — collect ten first, then look at them together. Changing a
rule to fix one case is how a rule table becomes a pile of exceptions.
`;

  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, doc, 'utf8');

  const failures = authored.filter((r) => !r.agrees);
  console.log(`authored: ${rate(authored)}   field: ${rate(field)}`);
  console.log(`Wrote ${outPath}`);

  if (failures.length) {
    console.error(`\n${failures.length} authored case(s) disagree — behaviour changed:`);
    for (const f of failures) {
      console.error(`  ${f.id}: expected ${f.expect}, got ${f.got}`);
    }
    process.exit(1);
  }
}

main();
